CREATE DATABASE IF NOT EXISTS TrondheimTheaterManagement;
USE TrondheimTheaterManagement;

CREATE TABLE IF NOT EXISTS Play (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255),
    Acts INT,
);

CREATE TABLE IF NOT EXISTS Performance (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PlayID INT,
    TheaterHall VARCHAR(255),
    PerformanceDate DATETIME,
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Seat (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PerformanceID: INT
    SeatNumber INT,
    SeatRow INT,
    Area VARCHAR(255),
    Available BOOLEAN,
    FOREIGN KEY (PerformanceID) REFERENCES Performance(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Customer (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerName VARCHAR(255),
    MobileNumber VARCHAR(20),
    CustomerAddress VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Ticket (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TicketType ENUM('REGULAR', 'STUDENT', 'HONOUR', 'GROUP', 'GROUP HONOR'),
    SeatID INT,
    CustomerID INT,
    FOREIGN KEY (SeatID) REFERENCES Seat(ID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(ID)
);

CREATE TABLE IF NOT EXISTS TheaterRole (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RoleName VARCHAR(255),
    PlayID INT,
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Actor (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PlayID INT,
    ActorName VARCHAR(255),
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Contributor (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PlayID INT,
    ContributorName VARCHAR(255),
    Email VARCHAR(255),
    TaskID INT,
    EmployeeStatus ENUM('Permanent', 'Temporary', 'Contractor', 'Extra/Volunteer'),
    FOREIGN KEY (TaskID) REFERENCES Task(ID),
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Task (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PresentIn (
    RoleID INT,
    Act INT,
    PRIMARY KEY (RoleID, Act),
    FOREIGN KEY (RoleID) REFERENCES Role(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PlayedBy (
    ActorID INT,
    RoleID INT,
    PRIMARY KEY (ActorID, RoleID),
    FOREIGN KEY (ActorID) REFERENCES Actors(ID) ON UPDATE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES Role(ID) ON UPDATE CASCADE
);