CREATE TABLE IF NOT EXISTS Play (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title VARCHAR(255),
    Acts INTEGER
);

CREATE TABLE IF NOT EXISTS Performance (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlayID INTEGER,
    TheaterHall VARCHAR(255),
    PerformanceDate DATETIME,
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Seat (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PerformanceID INTEGER,
    SeatNumber INTEGER,
    SeatRow INTEGER,
    Area VARCHAR(255),
    Available BOOLEAN,
    FOREIGN KEY (PerformanceID) REFERENCES Performance(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Customer (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerName VARCHAR(255),
    MobileNumber VARCHAR(20),
    CustomerAddress VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Ticket (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TicketType TEXT CHECK( TicketType IN ('REGULAR', 'STUDENT', 'HONOUR', 'GROUP', 'GROUP HONOR')),
    SeatID INTEGER,
    CustomerID INTEGER,
    FOREIGN KEY (SeatID) REFERENCES Seat(ID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(ID)
);

CREATE TABLE IF NOT EXISTS TheaterRole (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RoleName VARCHAR(255),
    PlayID INTEGER,
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Actor (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlayID INTEGER,
    ActorName VARCHAR(255),
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Contributor (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlayID INTEGER,
    ContributorName VARCHAR(255),
    Email VARCHAR(255),
    TaskID INTEGER,
    EmployeeStatus TEXT CHECK( EmployeeStatus IN ('Permanent', 'Temporary', 'Contractor', 'Extra/Volunteer')),
    FOREIGN KEY (TaskID) REFERENCES Task(ID),
    FOREIGN KEY (PlayID) REFERENCES Play(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Task (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PresentIn (
    RoleID INTEGER,
    Act INTEGER,
    PRIMARY KEY (RoleID, Act),
    FOREIGN KEY (RoleID) REFERENCES Role(ID) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PlayedBy (
    ActorID INTEGER,
    RoleID INTEGER,
    PRIMARY KEY (ActorID, RoleID),
    FOREIGN KEY (ActorID) REFERENCES Actors(ID) ON UPDATE CASCADE,
    FOREIGN KEY (RoleID) REFERENCES TheaterRole(ID) ON UPDATE CASCADE
);